application:
  subdomain: zeronews
  background_task: true
  public_path:
    - /
  routes:
    - /=file:///lzcapp/pkg/content/
services:
  zeronews:
    # zeronews/zeronews:v3.0.3
    # upstream: zeronews/zeronews:v3.0.3
    image: registry.lazycat.cloud/czyt/zeronews/zeronews:8b546f8ae2559bdd
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - TOKEN={{.U.zeronews_token}}
    binds:
      - /lzcapp/var/config:/etc/zeronews
    cpu_shares: 512
    mem_limit: 512M
