name: ZeroNews
package: cloud.lazycat.app.zeronews
version: 1.0.0
min_os_version: 1.3.8
description: "Edge cloud intranet penetration platform with high-performance tunnel protocol"
license: MIT
homepage: https://zeronews.cc
author: ZeroNews Team

application:
  subdomain: zeronews
  background_task: true
  public_path:
    - /
  routes:
    - /=file:///lzcapp/pkg/content/

services:
  zeronews:
    # zeronews/zeronews:latest
    image: registry.lazycat.cloud/czyt/zeronews/zeronews:4f226f4261dc7303
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - TOKEN={{.U.zeronews_token}}
    binds:
      - /lzcapp/var/config:/etc/zeronews
    restart: always
    cpu_shares: 512
    mem_limit: 512M

unsupported_platforms:
  - ios
  - android
  - tvos

locales:
  en:
    name: "ZeroNews"
    description: "Edge cloud intranet penetration platform with self-developed high-performance zeronews tunnel protocol for secure and fast access to internal network resources"
  zh:
    name: "ZeroNews"
    description: "边缘云内网穿透平台，采用自研高性能 zeronews tunnel 协议，实现内网与外网之间的安全、快速访问"
